name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Build and upload release zip
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZIP integration dir
        run: |
          cd ${{ github.workspace }}/custom_components/wapda_monitor
          zip wapda_monitor.zip -r ./

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/wapda_monitor/wapda_monitor.zip
